python cleanCSV_v2.py A.csv 
python cleanCSV_v2.py B.csv
python cleanCSV_v2.py C.csv
python cleanCSV_v2.py D.csv
python cleanCSV_v2.py E.csv
python cleanCSV_v2.py F.csv
python cleanCSV_v2.py G.csv
python cleanCSV_v2.py H.csv
python cleanCSV_v2.py I.csv
python cleanCSV_v2.py J.csv
python cleanCSV_v2.py K.csv
python cleanCSV_v2.py L.csv
python cleanCSV_v2.py M.csv
python cleanCSV_v2.py N.csv
python cleanCSV_v2.py O.csv
python cleanCSV_v2.py P.csv
python cleanCSV_v2.py Q.csv
python cleanCSV_v2.py R.csv
python cleanCSV_v2.py S.csv
python cleanCSV_v2.py T.csv
python cleanCSV_v2.py U.csv
python cleanCSV_v2.py V.csv
python cleanCSV_v2.py W.csv
python cleanCSV_v2.py X.csv
python cleanCSV_v2.py Y.csv
python cleanCSV_v2.py Z.csv
python cleanCSV_v2.py NUMBERS.csv
